# Generated by Django 3.0.8 on 2020-07-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript_analyzer', '0002_auto_20200713_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
