# Generated by Django 3.0.8 on 2020-07-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript_analyzer', '0003_character_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='picture',
            field=models.CharField(max_length=1000),
        ),
    ]
