# Generated by Django 3.0.8 on 2020-07-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript_analyzer', '0004_auto_20200717_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='character',
            name='picture',
            field=models.CharField(max_length=1000),
        ),
    ]
