# Generated by Django 3.0.8 on 2020-08-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcript_analyzer', '0006_auto_20200803_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='picture',
            field=models.CharField(max_length=100000),
        ),
    ]
